export enum CartActionType {
    ADD_ITEMS_TO_CART = 'ADD_ITEMS_TO_CART',
    SET_CART_ITEM_QUANTITY = 'SET_CART_ITEM_QUANTITY',
    DECREASE_ITEMS_FROM_CART = 'DECREASE_ITEMS_FROM_CART',
    REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART',
    RESET_CART = 'RESET_CART'
}